name: zdream
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  - ruff

  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - tensorboard

  - numpy=1.23.5

  - gymnasium
  - onnx

  - pyyaml
  - python-dotenv

  - pip:
      - stable-baselines3[extra]
      - mlagents
      - mlagents-envs
      - protobuf<4.0.0
